### ISSUE TITLE
No Basics.app...

### ISSUE THREAD

**Issue by theoknock** [b-yng/Basics#2]
There is no Basics.app in the download—just an Xcode project; and, when I built the Xcode project and ran the app, nothing happened in Xcode or otherwise...

**Comment by b-yng** [comment]
@theoknock You have to download the latest release's package zip. Not the source code option. Here's a direct link to [1.0.1](https://github.com/b-yng/Basics/releases/download/v1.0.1/XcodeBasics_1_0_1.zip).
